sonar.host.url=https://sonarcloud.io
sonar.organization=valossa515
sonar.projectKey=Valossa515_spring-courier
sonar.projectName=spring-courier
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/build/**,**/generated-sources/**,**/out/**
sonar.test.exclusions=**/target/**,**/build/**,**/generated-sources/**,**/out/**
sonar.coverage.exclusions=**/config/**,**/*Configuration.java,**/dto/**,**/model/**,**/entity/**,**/generated/**