sonar.host.url=https://sonarcloud.io
sonar.organization=valossa515
sonar.projectKey=Valossa515_spring-courier
sonar.projectName=spring-courier
sonar.sourceEncoding=UTF-8

# Paths
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Test & coverage reports
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions (ajuste conforme necessidade do projeto)
sonar.exclusions=**/target/**,**/build/**,**/generated-sources/**,**/out/**
sonar.test.exclusions=**/target/**,**/build/**,**/generated-sources/**,**/out/**
sonar.coverage.exclusions=**/config/**,**/*Configuration.java,**/dto/**,**/model/**,**/entity/**,**/generated/**

# Linguagens adicionais (se houver)
# sonar.sources=src/main/java,src/main/resources