blank_issues_enabled: true
contact_links:
  - name: 💬 Discussões
    url: https://github.com/Valossa515/spring-courier/discussions
    about: Use as discussões para perguntas, ideias e conversas gerais.
