apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-courier-cd
  namespace: argocd
  labels:
    app: spring-courier
    component: cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/valossa515/spring-courier.git
    targetRevision: main
    path: argo/workflows

  destination:
    server: https://kubernetes.default.svc
    namespace: spring-courier

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
